version: '2'
services:
    amrs:
        container_name: ampath_amrs_prod
        image: 10.50.80.56:5005/openmrs:2.1.2
        env_file: main.env
        volumes:
            - /home/achachiez/Code/openmrs-home:/root/.OpenMRS
        restart: unless-stopped
        # deploy:
        #   mode: replicated
        #   replicas: 1
        #   placement:
        #     constraints:
        #      - node.hostname == upgrade1
        ports:
            - 8080:8080