version: '2'
services:
    kenyaemr:
        container_name: kenyaemr
        image: 10.50.80.56:5005/kenyaemr:17.0.4
        env_file: main.env
        volumes:
             - ./openmrs:/root/.OpenMRS
        restart: unless-stopped
        # deploy:
        #   mode: replicated
        #   replicas: 1
        #   placement:
        #     constraints:
        #      - node.hostname == upgrade1
        ports:
            - 8080:8080