version: '3'
services:
    amrs-afyastat:
        container_name: amrs-afyastat
        image: ampathke/openmrs2.4.0:afyastat
        env_file: ./afyastat/main.env
        volumes:
            - ./afyastat:/root/.OpenMRS
        restart: unless-stopped
        ports:
            - 8083:8080
        dns:
           - 8.8.8.8
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8081/amrs/"]
            timeout: 20s