version: '2.1'
services:
    amrs-ocl:
        container_name: amrs-ocl
        image: ampathke/amrs-ocl
        depends_on:
             - ocl-mysql
        env_file: main.env
        volumes:
             - ./openmrs:/root/.OpenMRS
        restart: "always"
        ports:
            - 8080:8080
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/openmrs/"]
            timeout: 20s
    ocl-mysql:
        restart: "always"
        image: mysql:5.6
        command: "mysqld --character-set-server=utf8 --collation-server=utf8_general_ci"
        environment:
         MYSQL_DATABASE: ${MYSQL_DB:-amrsocl}
         MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-Admin123}
         MYSQL_USER: ${MYSQL_USER:-openmrs}
         MYSQL_PASSWORD: ${MYSQL_PASSWORD:-Admin123}
        healthcheck:
            test: "exit 0"
        volumes:
             - ./db:/var/lib/mysql
             - ./dbdump:/docker-entrypoint-initdb.d
        ports:
             - "3306:3306"