-- MySQL dump 10.13  Distrib 5.7.25, for Linux (x86_64)
--
-- Host: localhost    Database: demo2
-- ------------------------------------------------------
-- Server version	5.7.25-0ubuntu0.16.04.2

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `muzima_setting`
--

DROP TABLE IF EXISTS `muzima_setting`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `muzima_setting` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `property` varchar(255) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `description` varchar(1024) DEFAULT NULL,
  `value_boolean` tinyint(4) DEFAULT NULL,
  `value_string` varchar(255) DEFAULT NULL,
  `setting_data_type` varchar(255) NOT NULL,
  `creator` int(11) NOT NULL,
  `date_created` datetime NOT NULL,
  `changed_by` int(11) DEFAULT NULL,
  `date_changed` datetime DEFAULT NULL,
  `retired` tinyint(4) NOT NULL DEFAULT '0',
  `retired_by` int(11) DEFAULT NULL,
  `date_retired` datetime DEFAULT NULL,
  `retire_reason` varchar(255) DEFAULT NULL,
  `uuid` char(38) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uuid` (`uuid`),
  UNIQUE KEY `property` (`property`),
  KEY `muzima_setting_creator` (`creator`),
  KEY `muzima_setting_changed_by` (`changed_by`),
  KEY `muzima_setting_retired_by` (`retired_by`),
  CONSTRAINT `muzima_setting_changed_by` FOREIGN KEY (`changed_by`) REFERENCES `users` (`user_id`),
  CONSTRAINT `muzima_setting_creator` FOREIGN KEY (`creator`) REFERENCES `users` (`user_id`),
  CONSTRAINT `muzima_setting_retired_by` FOREIGN KEY (`retired_by`) REFERENCES `users` (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `muzima_setting`
--

LOCK TABLES `muzima_setting` WRITE;
/*!40000 ALTER TABLE `muzima_setting` DISABLE KEYS */;
INSERT INTO `muzima_setting` VALUES (1,'PatientIdentifier.AutoGeneration','Patient Identifier auto-generation','Defines whether or not patient patient identifier should be autogenerated during processing mUzima registration data. This should be set to \'true\' if autogeneration is needed',0,NULL,'BOOLEAN',1,'2017-09-22 00:00:00',1,'2019-10-01 11:45:08',0,NULL,NULL,NULL,'2a277ceb-7f23-4cc0-9e9b-1686985df121'),(2,'PatientIdentifier.AutoGenerationSourceName','Patient Identifier auto-generation Source name','Specifies name of auto-generation source defined in ID-GEN module',0,'Test source 2','STRING',1,'2017-10-17 00:00:00',1,'2018-02-03 15:43:39',0,NULL,NULL,NULL,'aae1a60f-f6ac-4d00-8af7-80270d715114'),(3,'AudioContentComplexObs.ConceptUuid','Concept Uuid for Complex Obs Audio Content','Specifies Concept Uuid for Complex Obs Audio Content',0,'c04d5513-d074-49f7-8c5f-06db45a250c9','STRING',1,'2018-07-17 11:56:00',1,'2019-02-15 16:03:20',0,NULL,NULL,NULL,'24caa622-691a-493b-b9ac-8ee70424ad47'),(4,'VideoContentComplexObs.ConceptUuid','Concept Uuid for Complex Obs Video Content','Specifies Concept Uuid for Complex Obs Video Content',0,'73033fee-d682-44fc-b0fc-aabf05aae0d7','STRING',1,'2018-07-17 12:00:00',1,'2019-02-15 16:04:07',0,NULL,NULL,NULL,'eaf882a3-3360-45b3-b480-ee9e634bc74f'),(5,'ImageContentComplexObs.ConceptUuid','Concept Uuid for Complex Obs Image Content','Specifies Concept Uuid for Complex Obs Image Content',0,'157196a5-720a-4a6f-9cea-30e85727b182','STRING',1,'2018-07-17 12:02:00',1,'2019-02-15 16:04:40',0,NULL,NULL,NULL,'fd759595-6338-491b-ac37-62e699c1823c'),(6,'FileContentComplexObs.ConceptUuid','Concept Uuid for Complex Obs File Content','Specifies Concept Uuid for Complex Obs File Content',0,'4c1dcaeb-163e-474f-bca5-d6a23166bada','STRING',1,'2018-07-17 12:07:00',1,'2019-02-15 16:06:38',0,NULL,NULL,NULL,'651fc189-127f-4b4c-98f3-121ed5ad182e'),(7,'SHRStatus.isEnabled','SHR status','Specifies if smart card feature will be enabled on Android App',0,NULL,'BOOLEAN',1,'2018-08-31 00:00:00',1,'2019-10-01 11:45:32',0,NULL,NULL,NULL,'25e52b76-dbef-4629-aed2-5497a1f8303c'),(8,'GPSStatus.isEnabled','GPS status','Specifies if GPS tracking feature will be activated on mUzima mobile application',1,NULL,'BOOLEAN',1,'2018-09-27 00:00:00',1,'2019-11-08 09:30:51',0,NULL,NULL,NULL,'7c5f3458-c240-11e8-a355-529269fb145i'),(9,'PatientReport.isEnabled','Patient Report Download Status','Whether patient reports will be downloaded to mobile device',0,NULL,'BOOLEAN',1,'2018-06-20 00:00:00',1,'2019-10-01 11:43:29',0,NULL,NULL,NULL,'aae1a60f-f6ac-4d00-ffff-80270d715114'),(15,'MediaWrapperConcept.ConceptUuid','Uuid for Media Wrapper Concept','Specifies Concept-Uuid for convenient set concept that wraps media complex obs with its metadata',0,'a2185311-bcca-4e12-ac8d-30f317512e80','STRING',1,'2019-02-14 13:53:00',1,'2019-02-28 07:35:24',0,NULL,NULL,NULL,'b7c0c988-3047-11e9-873e-d0577bcb2fe6'),(16,'MediaCategoryOtherNonCoded.ConceptUuid','Concept Uuid for other non-coded category','Specifies Concept-Uuid for concept-set other non-coded option for media category',0,'f0b64dd4-89df-4039-9890-4270f82fa6dd','STRING',1,'2019-02-14 13:56:00',1,'2019-02-28 07:38:39',0,NULL,NULL,NULL,'f81e3970-3047-11e9-873e-d0577bcb2fe6'),(17,'MediaContentComment.ConceptUuid','Concept Uuid for Media Content Comment','Specifies Concept-Uuid for media comment concept',0,'53f91b88-bc64-4310-b3f9-7b13679ac40b','STRING',1,'2019-02-14 14:03:00',1,'2019-02-28 07:37:40',0,NULL,NULL,NULL,'235e34e6-3048-11e9-873e-d0577bcb2fe6'),(18,'MediaCategoryFreeText.ConceptUuid','Concept Uuid for Other category text','Specifies Concept-Uuid for free text for other-non coded category option',0,'968bdf50-79c5-439b-a575-91611fdb7cd8','STRING',1,'2019-02-20 10:30:00',1,'2019-02-28 07:37:05',0,NULL,NULL,NULL,'adbda0a4-34d5-11e9-8667-d0577bcb2fe6'),(19,'MediaTitle.ConceptUuid','Concept Uuid for the title of the media','Specifies Concept-Uuid for the title of the media uploaded',0,'ad36eefa-f048-494e-ab93-e1cdb9ec48c9','STRING',1,'2019-04-18 09:45:00',1,'2019-04-18 09:58:09',0,NULL,NULL,NULL,'0080ecb8-61a6-11e9-a5ac-d0577bcb2fe6'),(20,'Relationships.isEnabled','Relationships status','Specifies if Relationships feature will be enabled for this implementation',1,NULL,'BOOLEAN',1,'2019-08-29 17:27:00',1,'2019-11-13 12:56:55',0,NULL,NULL,NULL,'f8c4ea54-9e8f-4f47-86c1-ab52f0bc719f');
/*!40000 ALTER TABLE `muzima_setting` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2019-11-15 12:22:56
